config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'home#index'
  resources :restaurants, only: [:new, :create, :show, :edit, :update]
  resources :dishes, only: [:index, :show, :edit, :update, :new, :create, :destroy]
  resources :beverages, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :tag_models, only: [:index, :new, :create, :show]
  
  resources :items, only: [] do 
    resources :portions, only: [:new, :create, :edit, :update]
    get 'search', on: :collection
    post 'disable', on: :member
    post 'enable', on: :member
  end

end

app/models/beverage.rb
class Beverage < Item 
  validates :alcoholic, inclusion: { in: [true, false], message: "Deve informar se a bebida é alcoólica ou não" }
end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController
  before_action :set_beverage_check_user, only: [:show, :edit, :update, :destroy]
  def index 
    @restaurant = current_user.restaurant
    @beverages = @restaurant.beverages
  end

  def show 
  end

  def new 
    @beverage = Beverage.new
  end

  def create 
    beverage_params = params.require(:beverage).permit(:name, :description, :calories, :alcoholic, :photo)
    @beverage = Beverage.new(beverage_params)
    @beverage.restaurant = current_user.restaurant

    if @beverage.save 
      redirect_to @beverage, notice: 'Bebida cadastrada com sucesso'
    else
      flash.now[:alert] = "Não foi possível registrar a bebida."
      render :new
    end
  end

  def edit
  end

  def update
    beverage_params = params.require(:beverage).permit(:name, :description, :calories, :alcoholic, :photo)
    if @beverage.update(beverage_params)
      redirect_to @beverage, notice: 'Bebida editada com sucesso'
    else
      flash.now[:alert] = "Não foi possível editar a bebida"
      render :edit
    end
  end

  def destroy
    if @beverage.destroy 
      redirect_to beverages_path, notice: 'Bebida removida com sucesso'
    else
      flash.now[:alert] = "Não foi possível remover a bebida."
      render :index
    end
  end

  private 
  def set_beverage_check_user
    @beverage = Beverage.find(params[:id])
    if @beverage.restaurant.user != current_user
      redirect_to root_path, alert: 'Você não possui acesso a esta bebida'
    end
  end
end

app/views/beverages/_beverage.html.erb
<dl class="border-2 p-4">
    <div>
        <dt><%= link_to beverage.name,  beverage_path(beverage)%></dt>    
    </div>
    <div class="flex">
        <dt><%= Beverage.human_attribute_name(:restaurant_id)%>:</dt>
        <dd><%= beverage.restaurant.brand_name%></dd>    
    </div>
    <div class="flex">
        <dt><%= Beverage.human_attribute_name(:calories)%>:</dt>
        <dd><%= beverage.calories%></dd>    
    </div>
    <div class="flex">
        <dt><%= Beverage.human_attribute_name(:status)%>:</dt>
        <dd><%= I18n.translate beverage.status %></dd>
    </div>
    <div>
        <% if beverage.photo.attached? %>
            <%= image_tag beverage.photo, size: "300x300" %>
        <% end %>
    </div>
</dl>

app/views/beverages/_form.html.erb
<% if @beverage.errors.any? %>
    <p>Verifique os erros abaixo:</p>
    <ul>
    <%@beverage.errors.full_messages.each do |msg|%>
        <li><%= msg%></li>
    <%end%>
    </ul>
<%end%>

<%= form_with model:@beverage do |f|%>
    <div>
        <%= f.label :name%>
        <%= f.text_field :name%>
    </div>
    <div>
        <%= f.label :description%>
        <%= f.text_field :description%>
    </div>
    <div>
        <%= f.label :calories%>
        <%= f.number_field :calories%>
    </div>
    <div>
        <%= f.label :alcoholic %>
        <%= f.radio_button :alcoholic, true, id: "alcoholic_true" %> Sim
        <%= f.radio_button :alcoholic, false, id: "alcoholic_false" %> Não
    </div>
    <div>
        <div>
            <% if @beverage.photo.attached? %>
                <%= image_tag @beverage.photo, size: "300x300" %>
            <% end %>
        </div>
        <%= f.label :photo%>
        <%= f.file_field :photo%>
    </div>

    <%= f.submit 'Gravar'%>
<%end%>

app/views/beverages/edit.html.erb
<%= render 'form'%>

app/views/beverages/index.html.erb
<div class="flex min-w-full flex-col items-center gap-10"> 
    <h1 class="text-xl text-center">Minhas Bebidas</h1>

    <%= form_with(url: search_items_path,method: :get) do |f|%>
        <div class="text-center">
        <%= f.label :query, 'Buscar por item'%>
        </div>
        <div class="w-full rounded-md border-gray-200 py-2.5">
            <%= f.text_field :query%>
        </div>
        <div class="text-center w-full inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500">
            <%= f.submit 'Buscar'%>
        </div>
    <%end%>

    <div class="inline-block rounded border border-indigo-600 px-12 py-3 text-sm font-medium text-indigo-600 hover:bg-indigo-600 hover:text-white focus:outline-none focus:ring active:bg-indigo-500">
        <%= link_to 'Registrar Bebida', new_beverage_path%>
    </div>

    <% @beverages.each do |beverage|%>
        <%= render beverage%>
    <%end%>
</div>

app/views/beverages/new.html.erb
<h1>Registrar Bebida</h1>

<%= render 'form'%>

app/views/beverages/show.html.erb
<div class="flex flex-col gap-4 items-center w-screen">
  <h1 class="text-lg font-medium text-gray-900">Detalhes da Bebida</h1>

  <dl>   
      <dd>
        <% if @beverage.photo.attached? %>
          <%= image_tag @beverage.photo, size: "300x300" %>
        <% else %>
            <p>Sem foto disponível</p>
        <% end %>
      </dd>
      <h2 class="text-center text-lg font-medium text-gray-900"><%= Beverage.model_name.human%> <%= @beverage.name%></h2>
      <div class="flex">
        <dt><%= Beverage.human_attribute_name(:restaurant_id)%>:</dt>
        <dd><%= @beverage.restaurant.brand_name%></dd>    
      </div>
      <div>
        <dd><%= @beverage.description%></dd> 
      </div>
      <div class="flex">
        <dt><%= Beverage.human_attribute_name(:alcoholic)%>:</dt>
        <dd>
            <%if @beverage.alcoholic%>
            Sim 
            <%else%>
            Não
            <%end%>
        </dd> 
      </div>
      <div class="flex">
        <dt><%= Beverage.human_attribute_name(:calories)%>:</dt>
        <dd><%= @beverage.calories%>g</dd> 
      </div>
      <div class="flex">
        <dt><%= Beverage.human_attribute_name(:status)%>:</dt>
        <dd><%= I18n.translate @beverage.status %></dd>
      </div>
  </dl>

  <div class="flex gap-2 flex-wrap">
    <% @beverage.tag_models.each do |tag|%>
      <div class="whitespace-nowrap rounded-full bg-purple-100 px-2.5 py-0.5 text-sm text-purple-700">
        <%= tag.description%>
      </div>
    <%end%>
  </div>

  <div class="inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500">
    <%= link_to 'Adicionar Porção', new_item_portion_path(item_id: @beverage.id)%>
  </div>

  <div>
    <% if @beverage.portions.any?%>
    <h2 class="text-center text-xl font-bold">Porções</h2>
    <div class="flex gap-2 text-center">
      <% @beverage.portions.each do |portion|%>
        <div class="border-2 border-black px-4 py-8 bg-gray-200">
          <div class="w-64 h-64">
            <% if @beverage.photo.attached? %>
              <%= image_tag @beverage.photo %>
            <% else %>
                <p>Sem foto disponível</p>
            <% end %>
          </div>
          <h3 class="font-bold text-xl"><%= portion.description%></h3>
          <span>R$ <%= portion.current_price%></span>
        </div>
      <%end%>
    </div>
    <%end%>
  </div>

  <div class="inline-flex rounded-lg border border-gray-100 bg-gray-100 p-1">
    <div class="inline-block rounded-md px-4 py-2 text-sm text-gray-500 hover:text-gray-700 focus:relative">
      <% if @beverage.active? %>
        <%= button_to 'Desabilitar', disable_item_path(@beverage)%>  
      <%else%>
        <%= button_to 'Ativar', enable_item_path(@beverage)%>
      <%end%>
    </div>

    <div class="inline-block rounded-md px-4 py-2 text-sm text-gray-500 hover:text-gray-700 focus:relative">
      <%= link_to 'Editar', edit_beverage_path(@beverage)%>
    </div>
    <div class="inline-block rounded-md bg-white px-4 py-2 text-sm text-blue-500 shadow-sm focus:relative">
      <%= button_to 'Excluir', beverage_path(@beverage), method: :delete%>  
    </div>
  </div>
</div>