config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'home#index'
  resources :restaurants, only: [:new, :create, :show, :edit, :update]
  resources :dishes, only: [:index, :show, :edit, :update, :new, :create, :destroy]
  resources :beverages, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :tag_models, only: [:index, :new, :create, :show]
  
  resources :items, only: [] do 
    resources :portions, only: [:new, :create, :edit, :update]
    get 'search', on: :collection
    post 'disable', on: :member
    post 'enable', on: :member
  end

end

app/models/dish.rb
class Dish < Item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :restaurant
  has_one_attached :photo
  has_many :portions
  has_many :item_tags
  has_many :tag_models, through: :item_tags

  enum :status, { active: 0, inactive: 1 }

  validates :name, :description, presence: true
  validates :calories, numericality: { only_integer: true }, allow_nil: true

  validate :acceptable_image

  private 
  def acceptable_image
    errors.add(:photo, "não deve ser vazia") unless photo.attached?

    acceptable_types = ["image/jpeg", "image/png", "image/webp", "image/jpg"]
    unless acceptable_types.include?(photo.content_type)
      errors.add(:photo, "deve ser JPEG ou PNG")
    end
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dish_check_user, only: [:show, :edit, :update, :destroy]
  def index
    @restaurant = current_user.restaurant
    @dishes = @restaurant.dishes
  end

  def new 
    @dish = Dish.new
    @tag_models = TagModel.all
  end

  def create 
    @dish = Dish.new(dish_params)
    @dish.restaurant = current_user.restaurant

    if @dish.save 
      redirect_to @dish, notice: 'Prato cadastrado com sucesso'
    else
      flash.now[:alert] = "Não foi possível registrar o prato."
      @tag_models = TagModel.all
      render :new
    end
  end
  def show
  end


  def edit 
    @tag_models = TagModel.all
  end

  def update
    if @dish.update(dish_params)
      redirect_to @dish, notice: 'Prato editado com sucesso'
    else
      flash.now[:alert] = "Não foi possível editar o prato."
      @tag_models = TagModel.all
      render :edit
    end
  end

  def destroy
    if @dish.destroy 
      redirect_to dishes_path, notice: 'Prato removido com sucesso'
    else
      flash.now[:alert] = "Não foi possível remover o prato."
      render :index
    end
  end

  private
  def set_dish_check_user 
    @dish = Dish.find(params[:id])
    if @dish.restaurant.user != current_user
      redirect_to root_path, alert: 'Você não possui acesso a este prato'
    end
  end

  def dish_params 
    params.require(:dish).permit(:name, :description, :calories, :photo, tag_model_ids: [])
  end
end

app/views/dishes/_dish.html.erb
<dl class="border-2 p-4">
    <div>
        <dt><%= link_to dish.name, dish_path(dish)%></dt>    
    </div>
    <div class="flex">
        <dt><%= Dish.human_attribute_name(:restaurant_id)%>:</dt>
        <dd><%= dish.restaurant.brand_name%></dd>    
    </div>
    <div class="flex">
        <dt><%= Dish.human_attribute_name(:calories)%>:</dt>
        <dd><%= dish.calories%></dd>    
    </div>
    <div class="flex">
        <dt><%= Dish.human_attribute_name(:status)%>:</dt>
        <dd><%= I18n.translate dish.status %></dd>
    </div>
    <div class="flex">
        <% if dish.photo.attached? %>
            <%= image_tag dish.photo, size: "300x300" %>
        <% end %>
    </div>
</dl>

app/views/dishes/_form.html.erb
<% if @dish.errors.any? %>
    <p>Verifique os erros abaixo:</p>
    <ul>
    <%@dish.errors.full_messages.each do |msg|%>
        <li><%= msg%></li>
    <%end%>
    </ul>
<%end%>

<%= form_with model:@dish do |f|%>
    <div>
        <%= f.label :name%>
        <%= f.text_field :name%>
    </div>
    <div>
        <%= f.label :description%>
        <%= f.text_field :description%>
    </div>
    <div>
        <%= f.label :calories%>
        <%= f.number_field :calories%>
    </div>
    <div>
        <div>
            <% if @dish.photo.attached? %>
                <%= image_tag @dish.photo, size: "300x300" %>
            <% end %>
        </div>
        <%= f.label :photo%>
        <%= f.file_field :photo%>
    </div>
    
    <div>
        <h3>Selecione os marcadores</h3>
        <%= f.collection_check_boxes :tag_model_ids, @tag_models, :id, :description do |b| %>
            <div>
            <%= b.check_box %>
            <%= b.label %>
            </div>
        <% end %>
        <%= link_to 'Adicionar Marcador', new_tag_model_path%>
    </div>
    <%= f.submit 'Gravar'%>
<%end%>

app/views/dishes/index.html.erb
<div class="flex min-w-full flex-col items-center gap-10">
    <h1 class="text-xl text-center">Meus Pratos</h1>

    <%= form_with(url: search_items_path,method: :get) do |f|%>
        <div class="text-center">
        <%= f.label :query, 'Buscar por item'%>
        </div>
        <div class="w-full rounded-md border-gray-200 py-2.5">
            <%= f.text_field :query%>
        </div>
        <div class="text-center w-full inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500">
            <%= f.submit 'Buscar'%>
        </div>
    <%end%>

    <div class="inline-block rounded border border-indigo-600 px-12 py-3 text-sm font-medium text-indigo-600 hover:bg-indigo-600 hover:text-white focus:outline-none focus:ring active:bg-indigo-500">
        <%= link_to 'Registrar Prato', new_dish_path%>
    </div>

    <% @dishes.each do |dish|%>
        <%= render dish%>
    <%end%>
</div>

app/views/dishes/new.html.erb
<h1>Registrar Prato</h1>

<%= render 'form'%>

app/views/dishes/show.html.erb
<div class="flex flex-col gap-4 items-center w-screen">
  <h1 class="text-lg font-medium text-gray-900">Detalhes do Prato</h1>

  <dl>   
      <dd>
        <% if @dish.photo.attached? %>
          <%= image_tag @dish.photo, size: "300x300" %>
        <% else %>
            <p>Sem foto disponível</p>
        <% end %>
      </dd>
      <h2 class="text-center text-lg font-medium text-gray-900"><%= Dish.model_name.human%> <%= @dish.name%></h2>
      <div class="flex">
        <dt><%= Dish.human_attribute_name(:restaurant_id)%>:</dt>
        <dd><%= @dish.restaurant.brand_name%></dd>    
      </div>
      <div>
        <dd><%= @dish.description%></dd> 
      </div>
      <div class="flex">
        <dt><%= Dish.human_attribute_name(:calories)%>:</dt>
        <dd><%= @dish.calories%>g</dd> 
      </div>
      <div class="flex">
        <dt><%= Dish.human_attribute_name(:status)%>:</dt>
        <dd><%= I18n.translate @dish.status %></dd>
      </div>
  </dl>

  <div class="flex gap-2 flex-wrap">
    <% @dish.tag_models.each do |tag|%>
      <div class="whitespace-nowrap rounded-full bg-purple-100 px-2.5 py-0.5 text-sm text-purple-700">
        <%= tag.description%>
      </div>
    <%end%>
  </div>

  <div class="inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500">
    <%= link_to 'Adicionar Porção', new_item_portion_path(item_id: @dish.id)%>
  </div>

  <div>
    <% if @dish.portions.any?%>
    <h2 class="text-center text-xl font-bold">Porções</h2>
    <div class="flex gap-2 text-center">
      <% @dish.portions.each do |portion|%>
        <div class="border-2 border-black px-4 py-8 bg-gray-200 flex flex-col">
          <div class="w-64 h-64">
            <% if @dish.photo.attached? %>
              <%= image_tag @dish.photo %>
            <% else %>
                <p>Sem foto disponível</p>
            <% end %>
          </div>
          <h3 class="font-bold text-xl"><%= portion.description%></h3>
          <span>R$ <%= portion.current_price%></span>
          <div class="inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500">
            <%= link_to 'Editar Porção', edit_item_portion_path(@dish, portion)%>
          </div>
        </div>
      <%end%>
    </div>
    <%end%>
  </div>

  <div class="inline-flex rounded-lg border border-gray-100 bg-gray-100 p-1">
    <div class="inline-block rounded-md px-4 py-2 text-sm text-gray-500 hover:text-gray-700 focus:relative">
      <% if @dish.active? %>
        <%= button_to 'Desabilitar', disable_item_path(@dish)%>  
      <%else%>
        <%= button_to 'Ativar', enable_item_path(@dish)%>
      <%end%>
    </div>

    <div class="inline-block rounded-md px-4 py-2 text-sm text-gray-500 hover:text-gray-700 focus:relative">
      <%= link_to 'Editar', edit_dish_path(@dish)%>
    </div>
    <div class="inline-block rounded-md bg-white px-4 py-2 text-sm text-blue-500 shadow-sm focus:relative">
      <%= button_to 'Excluir', dish_path(@dish), method: :delete%> 
    </div>
  </div>
</div>