config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'home#index'
  resources :restaurants, only: [:new, :create, :show, :edit, :update]
  resources :dishes, only: [:index, :show, :edit, :update, :new, :create, :destroy]
  resources :beverages, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :tag_models, only: [:index, :new, :create, :show]
  
  resources :items, only: [] do 
    resources :portions, only: [:new, :create, :edit, :update]
    get 'search', on: :collection
    post 'disable', on: :member
    post 'enable', on: :member
  end

end

app/models/portion.rb
class Portion < ApplicationRecord
  belongs_to :item

  validates :description, presence: true
  validates :current_price, presence: true
  validates :description, uniqueness: {scope: :item_id}
end

app/controllers/portions_controller.rb
class PortionsController < ApplicationController 
  before_action :set_item, only: [:new, :create, :edit, :update]
  before_action :set_portion_and_check_user, only: [:edit, :update]
  def new 
    @portion = @item.portions.build
  end

  def create     
    @portion = @item.portions.new(portion_params)
    
    if @portion.save
      redirect_to @item, notice: 'Porção criada com sucesso'
    else
      flash.now[:alert] = 'Não foi possível registrar a porção'
      render :new
    end
  end

  def edit 
  end

  def update 
    if @portion.update(portion_params)
      redirect_to @item, notice: 'Porção atualizada com sucesso'
    else
      flash.now[:alert] = 'Não foi possível atualizar a porção'
      render :edit 
    end
  end

  private 
  def set_item 
    @item = Item.find(params[:item_id])
  end

  def set_portion_and_check_user 
    @portion = @item.portions.find(params[:id])
    if @portion.item.restaurant.user != current_user 
      redirect_to root_path, alert: 'Você não possui acesso a esta ação'
    end
  end

  def portion_params
    params.require(:portion).permit(:description, :current_price)
  end
end

app/views/portions/_form.html.erb
<div>
    <% if @portion.errors.any? %>
        <p>Verifique os erros abaixo:</p>
        <ul class="flex flex-col gap-2">
        <%@portion.errors.full_messages.each do |msg|%>
            <li class="text-red-500"><%= msg%></li>
        <%end%>
        </ul>
    <%end%>
</div>

<%= form_with model: @portion, url: @portion.new_record? ? item_portions_path(@item) : item_portion_path(@item, @portion) do |f|%>
    <div class="flex flex-col gap-7">
        <div>
            <%= f.label :description, "Descrição" %>
            <div class="peer border-none bg-transparent placeholder-transparent focus:border-transparent focus:outline-none focus:ring-0">
                <%= f.text_field :description%>
            </div>
        </div>
        <div>
            <%= f.label :current_price, "Preço" %>
            <div class="peer border-none bg-transparent placeholder-transparent focus:border-transparent focus:outline-none focus:ring-0">
                <%= f.number_field :current_price, step: 0.01, min: 0 %>
            </div>
        </div>
        <div class="text-center block w-full rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white">
            <%= f.submit 'Enviar'%>
        </div>
    </div>
<%end%>

app/views/portions/edit.html.erb
<div class="flex flex-col gap-3 items-center justify-center w-screen">
    <h1 class="text-center text-xl text-black">Editar Porção</h1>

    <%= render 'form'%>
</div>

app/views/portions/new.html.erb
<div class="flex flex-col gap-3 items-center justify-center w-screen">
    <h1 class="text-center text-xl text-black">Cadastrar Porção</h1>

    <%= render 'form'%>
</div>