config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'home#index'
  resources :restaurants, only: [:new, :create, :show, :edit, :update]
  resources :dishes, only: [:index, :show, :edit, :update, :new, :create, :destroy]
  resources :beverages, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :tag_models, only: [:index, :new, :create, :show]
  
  resources :items, only: [] do 
    resources :portions, only: [:new, :create, :edit, :update]
    get 'search', on: :collection
    post 'disable', on: :member
    post 'enable', on: :member
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Paleva" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="flex justify-between bg-gray-100 p-3 items-center gap-5">
      <div>
        <%= link_to root_path do%>
          <h1>PaLevá</h1>
        <%end%>
      </div>
      <nav class="flex items-center gap-8">
        <% if user_signed_in? %>
          <%= link_to 'Meus Pratos', dishes_path%>
          <%= link_to 'Minhas Bebidas', beverages_path%>
          <%= link_to 'Modelos de Marcadores', tag_models_path%>
          <div class="inline-block rounded border border-red-600 bg-red-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-red-600 focus:outline-none focus:ring active:text-red-500">
            <%= button_to 'Sair', destroy_user_session_path, method: :delete%> 
          </div>
        <%end%> 
      </nav>
    </header>
    <main class="container mx-auto mt-28 px-5 flex flex-col gap-1 items-center">
      <div>
        <%= notice %>
        <%= alert %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>